spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    sql-migration-prefix: V
    sql-migration-separator: __
    url: ${DATABASE_URL}
pubsub:
  topic: ${IMAGE_TOPIC}

